### ISSUE TITLE
Unable to establish connection on channel

### ISSUE THREAD

**Issue by montonurb** [omchiii/model_viewer_plus.dart#55]
I'm running the following error:

E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebStorageHostApi.create
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebViewHostApi.create
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebSettingsHostApi.create
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebSettingsHostApi.setDomStorageEnabled
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebSettingsHostApi.setJavaScriptCanOpenWindowsAutomatically
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebSettingsHostApi.setSupportMultipleWindows
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebSettingsHostApi.setLoadWithOverviewMode
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebSettingsHostApi.setUseWideViewPort
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebSettingsHostApi.setDisplayZoomControls
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebSettingsHostApi.setBuiltInZoomControls
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebViewClientHostApi.create
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebSettingsHostApi.setUserAgentString
E/flutter (29494): <asynchronous suspension>
E/flutter (29494): #1      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
E/flutter (29494): <asynchronous suspension>
E/flutter (29494): #2      WebViewAndroidPlatformController.updateSettings
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebSettingsHostApi.setMediaPlaybackRequiresUserGesture
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebViewHostApi.setBackgroundColor
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      DownloadListenerHostApi.create
E/flutter (29494): <asynchronous suspension>
E/flutter (29494): #1      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
E/flutter (29494): <asynchronous suspension>
E/flutter (29494): #2      WebView.setDownloadListener
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
E/flutter (29494): #0      WebChromeClientHostApi.create
E/flutter (29494): <asynchronous suspension>
E/flutter (29494): #1      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
E/flutter (29494): <asynchronous suspension>
E/flutter (29494): #2      WebView.setWebChromeClient
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
E/flutter (29494): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter (29494): 	at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:143)
E/flutter (29494): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter (29494): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (29494): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter (29494): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/flutter (29494): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/flutter (29494): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/flutter (29494): 	at android.os.Handler.handleCallback(Handler.java:914)
E/flutter (29494): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/flutter (29494): 	at android.os.Looper.loop(Looper.java:225)
E/flutter (29494): 	at android.app.ActivityThread.main(ActivityThread.java:7564)
E/flutter (29494): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (29494): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/flutter (29494): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter (29494): , null, null)
E/flutter (29494): #0      StandardMethodCodec.decodeEnvelope
E/flutter (29494): #1      MethodChannel._invokeMethod
E/flutter (29494): <asynchronous suspension>
E/flutter (29494): #2      AndroidViewController.create
E/flutter (29494): <asynchronous suspension>
E/flutter (29494):
Restarted application in 2.841ms.

**Comment by z759341385** [comment]
i have same problem :(
any progress ?
